---
title: "Untitled"
author: "tom carroll"
date: "24 March 2017"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
    toc: true
    toc_depth: 1
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## BasecallQC

summaryConvStatsTable
```{r LaneT,fig.height=10,fig.width=10}
summaryConvStatsTable(BCLQCreport,output="html")
```

```{r Lane,fig.height=10,fig.width=10}
passFilterBar(BCLQCreport,groupBy = "Sample",
              metricToPlot = "Yield")+theme_bw()


```

```{r Sample,fig.height=10,fig.width=10}
passFilterBoxplot(BCLQCreport,groupBy = "Sample",
              metricToPlot = "Yield")+theme_bw()
```

```{r Sample2,fig.height=10,fig.width=10}
passFilterTilePlot(BCLQCreport,
              metricToPlot = "Yield")
```

```{r table,fig.height=10,fig.width=10}
summaryDemuxTable(BCLQCreport,output="html")
```

```{r tile,fig.height=10,fig.width=10}
demuxBarplot(BCLQCreport,groupBy = "Sample")+theme_bw()
```

```{r tile2,fig.height=10,fig.width=10}
demuxBoxplot(BCLQCreport,groupBy = "Sample")+theme_bw()
```

```{r fastqc,fig.height=30,fig.width=15}
if(doFQQC==TRUE){
  makeFQTable(BCLQCreport)
}
```
